ROBOT_ID = 'dsr01'
ROBOT_MODEL = 'mo6o9'
# ROBOT_TOOL = 'Tool Weight_2FG'
# ROBOT_TOOL = 'Tool Weight_RG2'
ROBOT_TOOL = 'Tool Weight'
# ROBOT_TCP = '2FG_TCP'
# ROBOT_TCP = 'RG2_TCP'
ROBOT_TCP = 'GripperDA_v1'
VEL = 100
ACC = 100
DRAWING_PATH = '/multi_stroke_drawing_path'
SAMPLE_THRESHOLD = 127
SAMPLE_RATIO = 0.1